"""empty message

Revision ID: efbe0cacd31b
Revises: 
Create Date: 2019-05-12 10:18:09.923946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efbe0cacd31b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('business', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.drop_column('business', 'creation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('business', 'updated_on')
    op.drop_column('business', 'created_on')
    # ### end Alembic commands ###
